### ISSUE TITLE
Add Linux Make section to the README

### ISSUE THREAD

**Issue by pbkoob** [unixtools/authsrv#2]
The README could use a little more love.  I would recommend adding the following:

Linux Builds:
---------------

Install has a dependency on libopenssl-devel, so please install that first.

Check out and build authsrv
	cd /work
	git clone https://github.com/unixtools/authsrv
	cd authsrv
	make
        make install
        cd unix
        make key

**Comment by nneul** [comment]
Added additional readme details.
